//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfoManageEntities : DbContext
    {
        public InfoManageEntities()
            : base("name=InfoManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Info_Account> Info_Account { get; set; }
        public virtual DbSet<ZYF_JG_GYS> ZYF_JG_GYS { get; set; }
        public virtual DbSet<ZYF_JG_YF> ZYF_JG_YF { get; set; }
        public virtual DbSet<ZYF_JG_YFKC> ZYF_JG_YFKC { get; set; }
        public virtual DbSet<ZYF_JG_YP> ZYF_JG_YP { get; set; }
        public virtual DbSet<ZYF_QT_DD> ZYF_QT_DD { get; set; }
        public virtual DbSet<ZYF_QT_TH> ZYF_QT_TH { get; set; }
        public virtual DbSet<ZYF_QT_XX> ZYF_QT_XX { get; set; }
        public virtual DbSet<ZYF_QT_YFPZ> ZYF_QT_YFPZ { get; set; }
        public virtual DbSet<ZYF_YH> ZYF_YH { get; set; }
        public virtual DbSet<ZYF_QT_RL> ZYF_QT_RL { get; set; }
    }
}
