namespace mingrisoft_3_
{
    partial class stock
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.plot = new NPlot.Windows.PlotSurface2D();
            this.btnIns = new System.Windows.Forms.Button();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.btnrefesh = new System.Windows.Forms.Button();
            this.panelPlot = new System.Windows.Forms.Panel();
            this.BtnClearDb = new System.Windows.Forms.Button();
            this.BtnReadDb = new System.Windows.Forms.Button();
            this.LblTips = new System.Windows.Forms.Label();
            this.panelPlot.SuspendLayout();
            this.SuspendLayout();
            // 
            // plot
            // 
            this.plot.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.plot.AutoScaleAutoGeneratedAxes = false;
            this.plot.AutoScaleTitle = false;
            this.plot.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.plot.DateTimeToolTip = false;
            this.plot.Legend = null;
            this.plot.LegendZOrder = -1;
            this.plot.Location = new System.Drawing.Point(3, 3);
            this.plot.Name = "plot";
            this.plot.RightMenu = null;
            this.plot.ShowCoordinates = true;
            this.plot.Size = new System.Drawing.Size(549, 306);
            this.plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this.plot.TabIndex = 0;
            this.plot.Text = "plotSurface2D1";
            this.plot.Title = "";
            this.plot.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.plot.XAxis1 = null;
            this.plot.XAxis2 = null;
            this.plot.YAxis1 = null;
            this.plot.YAxis2 = null;
            // 
            // btnIns
            // 
            this.btnIns.Location = new System.Drawing.Point(12, 12);
            this.btnIns.Name = "btnIns";
            this.btnIns.Size = new System.Drawing.Size(132, 23);
            this.btnIns.TabIndex = 1;
            this.btnIns.Text = "csv文件新数据录入";
            this.btnIns.UseVisualStyleBackColor = true;
            this.btnIns.Click += new System.EventHandler(this.BtnIns_Click);
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // btnrefesh
            // 
            this.btnrefesh.Location = new System.Drawing.Point(161, 12);
            this.btnrefesh.Name = "btnrefesh";
            this.btnrefesh.Size = new System.Drawing.Size(75, 23);
            this.btnrefesh.TabIndex = 2;
            this.btnrefesh.Text = "刷新蜡烛图";
            this.btnrefesh.UseVisualStyleBackColor = true;
            this.btnrefesh.Click += new System.EventHandler(this.Btnrefesh_Click);
            // 
            // panelPlot
            // 
            this.panelPlot.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelPlot.Controls.Add(this.plot);
            this.panelPlot.Location = new System.Drawing.Point(128, 102);
            this.panelPlot.Name = "panelPlot";
            this.panelPlot.Size = new System.Drawing.Size(555, 309);
            this.panelPlot.TabIndex = 3;
            // 
            // BtnClearDb
            // 
            this.BtnClearDb.Location = new System.Drawing.Point(14, 370);
            this.BtnClearDb.Name = "BtnClearDb";
            this.BtnClearDb.Size = new System.Drawing.Size(75, 23);
            this.BtnClearDb.TabIndex = 4;
            this.BtnClearDb.Text = "清空数据库";
            this.BtnClearDb.UseVisualStyleBackColor = true;
            this.BtnClearDb.Click += new System.EventHandler(this.BtnClearDb_Click);
            // 
            // BtnReadDb
            // 
            this.BtnReadDb.Location = new System.Drawing.Point(271, 12);
            this.BtnReadDb.Name = "BtnReadDb";
            this.BtnReadDb.Size = new System.Drawing.Size(75, 23);
            this.BtnReadDb.TabIndex = 5;
            this.BtnReadDb.Text = "读取数据";
            this.BtnReadDb.UseVisualStyleBackColor = true;
            this.BtnReadDb.Click += new System.EventHandler(this.BtnReadDb_Click);
            // 
            // LblTips
            // 
            this.LblTips.AutoSize = true;
            this.LblTips.Location = new System.Drawing.Point(12, 55);
            this.LblTips.Name = "LblTips";
            this.LblTips.Size = new System.Drawing.Size(23, 12);
            this.LblTips.TabIndex = 6;
            this.LblTips.Text = "Lbl";
            this.LblTips.Visible = false;
            // 
            // stock
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.LblTips);
            this.Controls.Add(this.BtnReadDb);
            this.Controls.Add(this.BtnClearDb);
            this.Controls.Add(this.panelPlot);
            this.Controls.Add(this.btnrefesh);
            this.Controls.Add(this.btnIns);
            this.IsMdiContainer = true;
            this.Name = "stock";
            this.Text = "stock";
            this.Load += new System.EventHandler(this.Stock_Load);
            this.panelPlot.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private NPlot.Windows.PlotSurface2D plot;
        private System.Windows.Forms.Button btnIns;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        private System.Windows.Forms.Button btnrefesh;
        private System.Windows.Forms.Panel panelPlot;
        private System.Windows.Forms.Button BtnClearDb;
        private System.Windows.Forms.Button BtnReadDb;
        private System.Windows.Forms.Label LblTips;
    }
}