//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_JG_GYS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZYF_JG_GYS()
        {
            this.ZYF_JG_YP = new HashSet<ZYF_JG_YP>();
        }
    
        public string GYSID { get; set; }
        public string GYSName { get; set; }
        public string GYSPerson { get; set; }
        public string GYSNum { get; set; }
        public string GYSCity { get; set; }
        public string GYSAddress { get; set; }
        public Nullable<System.DateTime> GYSBuildTime { get; set; }
        public Nullable<System.DateTime> GYSLastTrade { get; set; }
        public Nullable<int> GYSStar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_JG_YP> ZYF_JG_YP { get; set; }
    }
}
