//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_QT_YFPZ
    {
        public string YFPZID { get; set; }
        public string USERID { get; set; }
        public string YFID { get; set; }
    
        public virtual ZYF_YH ZYF_YH { get; set; }
    }
}
