//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_YH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZYF_YH()
        {
            this.ZYF_QT_DD = new HashSet<ZYF_QT_DD>();
            this.ZYF_QT_XX = new HashSet<ZYF_QT_XX>();
            this.ZYF_QT_YFPZ = new HashSet<ZYF_QT_YFPZ>();
        }
    
        public string USERID { get; set; }
        public string USERPassword { get; set; }
        public Nullable<System.DateTime> USERRegTime { get; set; }
        public Nullable<System.DateTime> USERLoginSuccTime { get; set; }
        public Nullable<System.DateTime> USERLoginFailTime { get; set; }
        public string USERWorkNum { get; set; }
        public string USERIC { get; set; }
        public string USERName { get; set; }
        public string USERJob { get; set; }
        public Nullable<int> USERSex { get; set; }
        public string USERNumber { get; set; }
        public string USERAddress { get; set; }
        public Nullable<int> USERPower { get; set; }
        public Nullable<int> USEROnJob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_DD> ZYF_QT_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_XX> ZYF_QT_XX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_YFPZ> ZYF_QT_YFPZ { get; set; }
    }
}
