//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_JG_YP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZYF_JG_YP()
        {
            this.ZYF_JG_YFKC = new HashSet<ZYF_JG_YFKC>();
            this.ZYF_QT_DD = new HashSet<ZYF_QT_DD>();
            this.ZYF_QT_XX = new HashSet<ZYF_QT_XX>();
        }
    
        public string YPID { get; set; }
        public string YPName { get; set; }
        public string YPImage { get; set; }
        public string YPKind { get; set; }
        public string GYSID { get; set; }
        public string YPRegTradeMark { get; set; }
        public string YPSaveStyle { get; set; }
        public Nullable<System.DateTime> YPBuildTime { get; set; }
        public Nullable<System.DateTime> YPLastUpdate { get; set; }
        public string YPSellUnit { get; set; }
        public string YPBarCode { get; set; }
    
        public virtual ZYF_JG_GYS ZYF_JG_GYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_JG_YFKC> ZYF_JG_YFKC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_DD> ZYF_QT_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_XX> ZYF_QT_XX { get; set; }
    }
}
