//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_JG_YF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZYF_JG_YF()
        {
            this.ZYF_JG_YFKC = new HashSet<ZYF_JG_YFKC>();
            this.ZYF_QT_XX = new HashSet<ZYF_QT_XX>();
        }
    
        public string YFID { get; set; }
        public string YFName { get; set; }
        public string YFImage { get; set; }
        public string YFAddress { get; set; }
        public Nullable<int> YFStar { get; set; }
        public Nullable<System.DateTime> YFRegTime { get; set; }
        public Nullable<int> YFOpen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_JG_YFKC> ZYF_JG_YFKC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_XX> ZYF_QT_XX { get; set; }
    }
}
