//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_QT_TH
    {
        public string THID { get; set; }
        public string DDID { get; set; }
        public Nullable<int> THNum { get; set; }
        public string THReason { get; set; }
    
        public virtual ZYF_QT_DD ZYF_QT_DD { get; set; }
    }
}
