//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mingrisoft_3_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZYF_QT_DD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZYF_QT_DD()
        {
            this.ZYF_QT_TH = new HashSet<ZYF_QT_TH>();
        }
    
        public string DDID { get; set; }
        public string USERID { get; set; }
        public string YPID { get; set; }
        public Nullable<int> DDNum { get; set; }
        public Nullable<decimal> DDPrice { get; set; }
        public string DDMedicalInsure { get; set; }
        public Nullable<System.DateTime> DDInsertTime { get; set; }
        public Nullable<System.DateTime> DDFinishTime { get; set; }
        public Nullable<System.DateTime> DDCancelTime { get; set; }
        public Nullable<int> DDFinish { get; set; }
    
        public virtual ZYF_JG_YP ZYF_JG_YP { get; set; }
        public virtual ZYF_YH ZYF_YH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZYF_QT_TH> ZYF_QT_TH { get; set; }
    }
}
